package com.example.greensnap.dbconexion

import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper
import androidx.core.content.ContextCompat.getString
import com.example.greensnap.R

class DBManager(private val context:Context, dbName:String, factory:SQLiteDatabase.CursorFactory?, dbVersion:Int): SQLiteOpenHelper(context,dbName,factory,dbVersion) {

    companion object {
        val DB_NAME = "greensnap.db3"
        val DB_VERSION = 1
    }

    constructor(context:Context):this(context, DB_NAME, null, DB_VERSION){}

    override fun onCreate(db: SQLiteDatabase) {

        db.execSQL("CREATE TABLE CUIDADOS (CODIGO_CUIDADOS INTEGER PRIMARY KEY NOT NULL, ILUMINACION TEXT, TEMPERATURA TEXT, SUSTRATO TEXT, RIEGO TEXT, HUMEDAD TEXT, ABONO TEXT, PODA TEXT, ENFERMEDADES TEXT, TRANSPLANTE TEXT)")
        db.execSQL("CREATE TABLE CATEGORIAS (ID_CATEGORIA INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, NOMBRE_CATEGORIA TEXT, DESCRIPCION TEXT, CODIGO_CUIDADOS INTEGER, FOREIGN KEY (CODIGO_CUIDADOS) REFERENCES CUIDADOS(CODIGO_CUIDADOS))")
        db.execSQL("CREATE TABLE PLANTAS(ID_PLANTA INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, NOMBRE_PLANTA TEXT, TIPO TEXT, IMAGEN TEXT, ID_CATEGORIA INTEGER, FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA))")
        db.execSQL("CREATE TABLE JARDIN (ID_PLANTA INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, NOMBRE_PLANTA TEXT)")
        db.execSQL("CREATE TABLE USUARIOS (ID_USUARIO INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, NOMBRE_USUARIO TEXT, CORREO TEXT, PASSWORD TEXT)")

        db.execSQL("INSERT INTO USUARIOS (NOMBRE_USUARIO, CORREO, PASSWORD) VALUES ('admin', 'admin@admin', 'admin')")

//        db.execSQL("INSERT INTO CUIDADOS (CODIGO_CUIDADOS, ILUMINACION, TEMPERATURA, SUSTRATO, RIEGO, HUMEDAD, ABONO, PODA, ENFERMEDADES, TRANSPLANTE) VALUES (10, '"+ getString(context,R.string.luz_azalea) + "', '" + getString(context,R.string.temperatura_azalea) + "', '" + getString(context, R.string.sustrato_azalea) + "', '" + getString(context, R.string.riego_azalea) + "', '" + getString(context, R.string.humedad_azalea) + "', '" + getString(context, R.string.abono_azalea) + "', '" + getString(context, R.string.poda_azalea) + "', '" + getString(context, R.string.enfermedades_azalea) + "', '" + getString(context, R.string.trasplante_azalea) + "')")
//        db.execSQL("INSERT INTO CUIDADOS (CODIGO_CUIDADOS, ILUMINACION, TEMPERATURA, SUSTRATO, RIEGO, HUMEDAD, ABONO, PODA, ENFERMEDADES, TRANSPLANTE) VALUES (20, '"+ getString(context, R.string.luz_begonia) + "', '" + getString(context, R.string.temperatura_begonia) + "', '" + getString(context, R.string.sustrato_begonia) + "', '" + getString(context, R.string.riego_begonia) + "', '" + getString(context, R.string.humedad_begonia) + "', '" + getString(context, R.string.abono_begonia) + "', '" + getString(context, R.string.poda_begonia) + "', '" + getString(context, R.string.enfermedades_begonia) + "', '" + getString(context, R.string.trasplante_begonia) + "')")
//        db.execSQL("INSERT INTO CUIDADOS (CODIGO_CUIDADOS, ILUMINACION, TEMPERATURA, SUSTRATO, RIEGO, HUMEDAD, ABONO, PODA, ENFERMEDADES, TRANSPLANTE) VALUES (30, '"+ getString(context, R.string.luz_cactus) + "', '" + getString(context, R.string.temperatura_begonia) + "', '" + getString(context, R.string.sustrato_cactus) + "', '" + getString(context, R.string.riego_cactus) + "', '" + getString(context, R.string.humedad_cactus) + "', '" + getString(context, R.string.abono_cactus) + "', '" + getString(context, R.string.poda_cactus) + "', '" + getString(context, R.string.enfermedades_cactus) + "', '" + getString(context, R.string.trasplante_cactus) + "')")
//        db.execSQL("INSERT INTO CUIDADOS (CODIGO_CUIDADOS, ILUMINACION, TEMPERATURA, SUSTRATO, RIEGO, HUMEDAD, ABONO, PODA, ENFERMEDADES, TRANSPLANTE) VALUES (40, '"+ getString(context, R.string.luz_calatheas) + "', '" + getString(context, R.string.temperatura_calatheas) + "', '" + getString(context, R.string.sustrato_calatheas) + "', '" + getString(context, R.string.riego_calatheas) + "', '" + getString(context, R.string.humedad_calatheas) + "', '" + getString(context, R.string.abono_calatheas) + "', '" + getString(context, R.string.poda_calatheas) + "', '" + getString(context, R.string.enfermedades_calatheas) + "', '" + getString(context, R.string.transplante_calatheas) + "')")
//        db.execSQL("INSERT INTO CUIDADOS (CODIGO_CUIDADOS, ILUMINACION, TEMPERATURA, SUSTRATO, RIEGO, HUMEDAD, ABONO, PODA, ENFERMEDADES, TRANSPLANTE) VALUES (50, '"+ getString(context, R.string.luz_crassula) + "', '" + getString(context, R.string.temperatura_crassula) + "', '" + getString(context, R.string.sustrato_crassula) + "', '" + getString(context, R.string.riego_crassula) + "', '" + getString(context, R.string.humedad_crassula) + "', '" + getString(context, R.string.abono_crassula) + "', '" + getString(context, R.string.poda_crassula) + "', '" + getString(context, R.string.enfermedades_crassula) + "', '" + getString(context,R.string.trasplante_crassula) + "')")
//        db.execSQL("INSERT INTO CUIDADOS (CODIGO_CUIDADOS, ILUMINACION, TEMPERATURA, SUSTRATO, RIEGO, HUMEDAD, ABONO, PODA, ENFERMEDADES, TRANSPLANTE) VALUES (60, '"+ getString(context, R.string.luz_dionaea) + "', '" + getString(context, R.string.temperatura_dionaea) + "', '" + getString(context, R.string.sustrato_dionaea) + "', '" + getString(context, R.string.riego_dionaea) + "', '" + getString(context, R.string.humedad_dionaea) + "', '" + getString(context, R.string.abono_dionaea) + "', '" + getString(context, R.string.poda_dionaea) + "', '" + getString(context, R.string.enfermedades_dionaea) + "', '" + getString(context, R.string.trasplante_dionaea) + "')")
//        db.execSQL("INSERT INTO CUIDADOS (CODIGO_CUIDADOS, ILUMINACION, TEMPERATURA, SUSTRATO, RIEGO, HUMEDAD, ABONO, PODA, ENFERMEDADES, TRANSPLANTE) VALUES (70, '"+ getString(context, R.string.luz_echeveria) + "', '" + getString(context, R.string.temperatura_echeveria) + "', '" + getString(context, R.string.sustrato_echeveria) + "', '" + getString(context, R.string.riego_echeveria) + "', '" + getString(context, R.string.humedad_echeveria) + "', '" + getString(context, R.string.abono_echeveria) + "', '" + getString(context, R.string.poda_echeveria) + "', '" + getString(context, R.string.enfermedades_echeveria) + "', '" + getString(context, R.string.trasplante_echeveria) + "')")
//        db.execSQL("INSERT INTO CUIDADOS (CODIGO_CUIDADOS, ILUMINACION, TEMPERATURA, SUSTRATO, RIEGO, HUMEDAD, ABONO, PODA, ENFERMEDADES, TRANSPLANTE) VALUES (80, '"+ getString(context, R.string.luz_euphorbia) + "', '" + (R.string.temperatura_euphorbia) + "', '" + getString(context, R.string.sustrato_euphorbia) + "', '" + getString(context, R.string.riego_euphorbia) + "', '" + getString(context, R.string.humedad_euphorbia) + "', '" + getString(context, R.string.abono_euphorbia) + "', '" + getString(context, R.string.poda_euphorbia) + "', '" + getString(context, R.string.enfermedades_euphorbia) + "', '" + getString(context, R.string.trasplante_euphorbia) + "')")
//        db.execSQL("INSERT INTO CUIDADOS (CODIGO_CUIDADOS, ILUMINACION, TEMPERATURA, SUSTRATO, RIEGO, HUMEDAD, ABONO, PODA, ENFERMEDADES, TRANSPLANTE) VALUES (90, '"+ getString(context, R.string.luz_guzmania) + "', '" + getString(context, R.string.temperatura_guzmania) + "', '" + getString(context, R.string.sustrato_guzmania) + "', '" + getString(context, R.string.riego_guzmania) + "', '" + getString(context, R.string.humedad_guzmania) + "', '" + getString(context, R.string.abono_guzmania) + "', '" + getString(context, R.string.poda_guzmania) + "', '" + getString(context, R.string.enfermedades_guzmania) + "', '" + getString(context, R.string.trasplante_guzmania) + "')")
//        db.execSQL("INSERT INTO CUIDADOS (CODIGO_CUIDADOS, ILUMINACION, TEMPERATURA, SUSTRATO, RIEGO, HUMEDAD, ABONO, PODA, ENFERMEDADES, TRANSPLANTE) VALUES (100, '"+ getString(context, R.string.luz_dianthus) + "', '" + getString(context, R.string.temperatura_dianthus) + "', '" + getString(context, R.string.sustrato_dianthus) + "', '" + getString(context, R.string.riego_dianthus) + "', '" + getString(context, R.string.humedad_dianthus) + "', '" + getString(context, R.string.abono_dianthus) + "', '" + getString(context, R.string.poda_dianthus) + "', '" + getString(context, R.string.enfermedades_dianthus) + "', '" + getString(context, R.string.trasplante_dianthus) + "')")
//        db.execSQL("INSERT INTO CUIDADOS (CODIGO_CUIDADOS, ILUMINACION, TEMPERATURA, SUSTRATO, RIEGO, HUMEDAD, ABONO, PODA, ENFERMEDADES, TRANSPLANTE) VALUES (110, '"+ getString(context, R.string.luz_dimorphotheca) + "', '" + getString(context, R.string.temperatura_dimorphotheca) + "', '" + getString(context, R.string.sustrato_dimorphotheca) + "', '" + getString(context, R.string.riego_dimorphotheca) + "', '" + getString(context, R.string.humedad_dimorphotheca) + "', '" + getString(context, R.string.abono_dimorphotheca) + "', '" + getString(context, R.string.poda_dimorphotheca) + "', '" + getString(context, R.string.enfermedades_dimorphotheca) + "', '" + getString(context, R.string.trasplante_dimorphoteca) + "')")
//        db.execSQL("INSERT INTO CUIDADOS (CODIGO_CUIDADOS, ILUMINACION, TEMPERATURA, SUSTRATO, RIEGO, HUMEDAD, ABONO, PODA, ENFERMEDADES, TRANSPLANTE) VALUES (120, '"+ getString(context, R.string.luz_violas) + "', '" + getString(context, R.string.temperatura_violas) + "', '" + getString(context, R.string.sustrato_violas) + "', '" + getString(context, R.string.riego_violas) + "', '" + getString(context, R.string.humedad_violas) + "', '" + getString(context, R.string.abono_violas) + "', '" + getString(context, R.string.poda_violas) + "', '" + getString(context, R.string.enfermedades_violas) + "', '" + getString(context, R.string.trasplante_violas) + "')")
//
//        db.execSQL("INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION, CODIGO_CUIDADOS) VALUES ('"+ getString(context, R.string.azaleas) + "', '" + getString(context, R.string.azaleas_descripcion) + "', 10)")
//        db.execSQL("INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION, CODIGO_CUIDADOS) VALUES ('" + getString(context, R.string.begonias) + "', '" + getString(context, R.string.begonias_descripcion) + "', 20)")
//        db.execSQL("INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION, CODIGO_CUIDADOS) VALUES ('" + getString(context, R.string.cactus) + "', '" + getString(context, R.string.cactus_descripcion) + "', 30)")
//        db.execSQL("INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION, CODIGO_CUIDADOS) VALUES ('" + getString(context, R.string.calatheas) + "', '" + getString(context, R.string.calatheas_descripcion) + "', 40)")
//        db.execSQL("INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION, CODIGO_CUIDADOS) VALUES ('" + getString(context, R.string.crassula) + "', '" + getString(context, R.string.crassula_descripcion) + "', 50)")
//        db.execSQL("INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION, CODIGO_CUIDADOS) VALUES ('" + getString(context, R.string.dionaea) + "', '" + getString(context, R.string.dionaea_descripcion) + "', 60)")
//        db.execSQL("INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION, CODIGO_CUIDADOS) VALUES ('" + getString(context, R.string.echeveria) + "', '" + getString(context, R.string.echeveria_descripcion) + "', 70)")
//        db.execSQL("INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION, CODIGO_CUIDADOS) VALUES ('" + getString(context, R.string.euphorbia) + "', '" + getString(context, R.string.euphorbia_descripcion) + "', 80)")
//        db.execSQL("INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION, CODIGO_CUIDADOS) VALUES ('" + getString(context, R.string.guzmania) + "', '" + getString(context, R.string.guzmania_descripcion) + "', 90)")
//        db.execSQL("INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION, CODIGO_CUIDADOS) VALUES ('" + getString(context, R.string.claveles) + "', '" + getString(context, R.string.claveles_descripcion) + "', 100)")
//        db.execSQL("INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION, CODIGO_CUIDADOS) VALUES ('" + getString(context, R.string.margaritas) + "', '" + getString(context, R.string.margaritas_descripcion) + "', 110)")
//        db.execSQL("INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION, CODIGO_CUIDADOS) VALUES ('" + getString(context, R.string.violas) + "', '" + getString(context, R.string.violas_descripcion) + "', 120)")

        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context,R.string.azalea_hortinno) + "', '" + getString(context,R.string.ambos) + "', 'azalea_hortinno', 1)")
        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context, R.string.azalea_hortinno_noralinde) + "', '" + getString(context, R.string.ambos) + "', 'azalea_hortinno_noralinde', 1)")
        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context, R.string.azalea_hortinno_yankadi) + "', '" + getString(context, R.string.ambos) + "', 'azalea_hortinno_yankadi', 1)")
        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context, R.string.azalea_piramide) + "', '" + getString(context, R.string.ambos) + "', 'azalea_piramide', 1)")
        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context, R.string.begonia_elatior_roja_baladin) + "', '" + getString(context, R.string.ambos) + "', 'begonia_elatior_roja_baladin', 2)")
        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context, R.string.begonia_elatior_roja_grace) + "', '" + getString(context, R.string.ambos) + "', 'begonia_elatior_roja_grace', 2)")
        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context, R.string.begonia_elatior_salmon) + "', '" + getString(context, R.string.ambos) + "', 'begonia_elatior_salmon_borias', 2)")
        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context, R.string.begonia_maculata) + "', '" + getString(context, R.string.ambos) + "', 'begonia_maculata_wightii', 2)")
        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context, R.string.cactus_navidad) + "', '" + getString(context, R.string.interior) + "', 'schlumbergera_cactus_de_navidad', 3)")
        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context, R.string.calathea_lancifolia) + "', '" + getString(context, R.string.interior) + "', 'calathea_lancifolia', 4)")
        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context, R.string.calathea_ornata) + "', '" + getString(context, R.string.interior) + "', 'calathea_ornata_sanderiana', 4)")
        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context, R.string.calathea_roseopicta) + "', '" + getString(context, R.string.interior) + "', 'calathea_roseopicta_medallion', 4)")
        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context, R.string.calathea_zebrina) + "', '" + getString(context, R.string.interior) + "', 'calathea_zebrina', 4)")
        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context, R.string.crassula_ovata) + "', '" + getString(context, R.string.ambos) + "', 'crassula_ovata_sunset', 5)")
        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context, R.string.dionaea_muscipula) + "', '" + getString(context, R.string.ambos) + "', 'dionaea_muscipula', 6)")
        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context, R.string.echeveria_pulvinata) + "', '" + getString(context, R.string.ambos) + "', 'echeveria_pulvinata', 7)")
        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context, R.string.euphorbia_milii) + "', '" + getString(context, R.string.ambos) + "', 'euphorbia_milii', 8)")
        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context, R.string.guzmania_francesca) + "', '" + getString(context, R.string.interior) + "', 'guzmania_francesca', 9)")
        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context, R.string.dianthus_barbatus) + "', '" + getString(context, R.string.ambos) + "', 'dianthus_barbatus_clavel_del_poeta', 10)")
        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context, R.string.dianthus_caryophyllus) + "', '" + getString(context, R.string.ambos) + "', 'dianthus_caryophyllus_clavel_comun', 10)")
        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context, R.string.dianthus_caryophyllus) + "', '" + getString(context, R.string.exterior) + "', 'dimorphotheca_ecklonis_margarita_del_cabo', 11)")
        db.execSQL("INSERT INTO PLANTAS (NOMBRE_PLANTA, TIPO, IMAGEN, ID_CATEGORIA) VALUES ('" + getString(context, R.string.viola_x_wittrockiana) + "', '" + getString(context, R.string.exterior) + "', 'viola_x_wittrockiana_planta_del_pensamiento', 12)")
    }

    override fun onUpgrade(db: SQLiteDatabase, oldVersion: Int, newVersion: Int) {
//        db.execSQL("DROP TABLE IF EXISTS CUIDADOS")
//        db.execSQL("DROP TABLE IF EXISTS CATEGORIAS")
//        db.execSQL("DROP TABLE IF EXISTS PLANTAS")
//        db.execSQL("DROP TABLE IF EXISTS JARDIN")
    }

}